// src/theme/lightThemeTokens.js

const lightThemeTokens = {
  colorPrimary: '#007BFF'
  // colorPrimaryBg: '#E6F7FF',
  // colorPrimaryBgHover: '#BAE7FF',
  // colorPrimaryBorder: '#91D5FF',
  // colorPrimaryBorderHover: '#69C0FF',
  // colorPrimaryHover: '#40A9FF',
  // colorPrimaryActive: '#096DD9',
  // colorPrimaryText: '#096DD9',
  // colorPrimaryTextHover: '#1890FF',
  // colorPrimaryTextActive: '#0050B3',
  // colorPrimaryTextDisabled: '#BFBFBF',
  // colorSuccess: '#52C41A',
  // colorSuccessBg: '#F6FFED',
  // colorSuccessBgHover: '#D9F7BE',
  // colorSuccessBorder: '#B7EB8F',
  // colorSuccessBorderHover: '#95DE64',
  // colorSuccessHover: '#73D13D',
  // colorSuccessActive: '#389E0D',
  // colorSuccessText: '#389E0D',
  // colorSuccessTextHover: '#52C41A',
  // colorSuccessTextActive: '#237804',
  // colorSuccessTextDisabled: '#D9D9D9',
  // colorWarning: '#FAAD14',
  // colorWarningBg: '#FFFBE6',
  // colorWarningBgHover: '#FFF1B8',
  // colorWarningBorder: '#FFE58F',
  // colorWarningBorderHover: '#FFD666',
  // colorWarningHover: '#FFC53D',
  // colorWarningActive: '#D48806',
  // colorWarningText: '#D48806',
  // colorWarningTextHover: '#FAAD14',
  // colorWarningTextActive: '#AD6800',
  // colorWarningTextDisabled: '#F5F5F5',
  // colorError: '#FF4D4F',
  // colorErrorBg: '#FFF2F0',
  // colorErrorBgHover: '#FFD7D7',
  // colorErrorBorder: '#FFCCC7',
  // colorErrorBorderHover: '#FFA39E',
  // colorErrorHover: '#FF7875',
  // colorErrorActive: '#D9363E',
  // colorErrorText: '#D9363E',
  // colorErrorTextHover: '#FF4D4F',
  // colorErrorTextActive: '#A8071A',
  // colorErrorTextDisabled: '#F5F5F5',
  // colorInfo: '#1890FF',
  // colorInfoBg: '#E6F7FF',
  // colorInfoBgHover: '#BAE7FF',
  // colorInfoBorder: '#91D5FF',
  // colorInfoBorderHover: '#69C0FF',
  // colorInfoHover: '#40A9FF',
  // colorInfoActive: '#096DD9',
  // colorInfoText: '#096DD9',
  // colorInfoTextHover: '#1890FF',
  // colorInfoTextActive: '#0050B3',
  // colorInfoTextDisabled: '#D9D9D9',
  // colorTextBase: '#000000',
  // colorTextSecondary: '#595959',
  // colorTextTertiary: '#8C8C8C',
  // colorTextDisabled: '#BFBFBF',
  // colorTextHeading: '#262626',
  // colorTextLabel: '#595959',
  // colorTextPlaceholder: '#BFBFBF',
  // colorFill: '#F5F5F5',
  // colorFillSecondary: '#FAFAFA',
  // colorFillTertiary: '#FFFFFF',
  // colorFillQuaternary: '#F0F0F0',
  // colorBgBase: '#FFFFFF',
  // colorBgContainer: '#FFFFFF',
  // colorBgElevated: '#FFFFFF',
  // colorBgLayout: '#F0F2F5',
  // colorBgSpotlight: '#F5F5F5',
  // colorBorder: '#D9D9D9',
  // colorBorderSecondary: '#E8E8E8',
  // colorBorderTertiary: '#F0F0F0',
  // colorBorderQuaternary: '#F5F5F5',
  // colorBorderBg: '#FFFFFF',
  // colorBgMask: 'rgba(0, 0, 0, 0.45)'
}

// src/theme/darkThemeTokens.js

const darkThemeTokens = {
  colorPrimary: '#007BFF',
  // colorPrimaryBg: '#111B26',
  colorPrimaryBgHover: '#112A45',
  // colorPrimaryBorder: '#15395B',
  // colorPrimaryBorderHover: '#1D4E8F',
  // colorPrimaryHover: '#2B6CB0',
  colorPrimaryActive: '#1D4E8F', //'#1C3D5A',
  colorPrimaryText: '#b8ddff',
  // colorPrimaryTextHover: '#40A9FF',
  // colorPrimaryTextActive: '#096DD9',
  // colorPrimaryTextDisabled: '#434343',
  // colorSuccess: '#52C41A',
  // colorSuccessBg: '#0C1F0A',
  // colorSuccessBgHover: '#173D12',
  // colorSuccessBorder: '#237804',
  // colorSuccessBorderHover: '#52C41A',
  // colorSuccessHover: '#73D13D',
  // colorSuccessActive: '#389E0D',
  // colorSuccessText: '#73D13D',
  // colorSuccessTextHover: '#95DE64',
  // colorSuccessTextActive: '#52C41A',
  // colorSuccessTextDisabled: '#434343',
  // colorWarning: '#FAAD14',
  // colorWarningBg: '#2B2111',
  // colorWarningBgHover: '#4D381A',
  // colorWarningBorder: '#AD6800',
  // colorWarningBorderHover: '#FAAD14',
  // colorWarningHover: '#FFC53D',
  // colorWarningActive: '#D48806',
  // colorWarningText: '#FFC53D',
  // colorWarningTextHover: '#FFD666',
  // colorWarningTextActive: '#FAAD14',
  // colorWarningTextDisabled: '#434343',
  // colorError: '#FF4D4F',
  // colorErrorBg: '#2A1215',
  // colorErrorBgHover: '#431418',
  // colorErrorBorder: '#A8071A',
  // colorErrorBorderHover: '#FF4D4F',
  // colorErrorHover: '#FF7875',
  // colorErrorActive: '#D9363E',
  // colorErrorText: '#FF7875',
  // colorErrorTextHover: '#FFA39E',
  // colorErrorTextActive: '#FF4D4F',
  // colorErrorTextDisabled: '#434343',
  // colorInfo: '#1890FF',
  // colorInfoBg: '#111B26',
  // colorInfoBgHover: '#112A45',
  // colorInfoBorder: '#15395B',
  // colorInfoBorderHover: '#1D4E8F',
  // colorInfoHover: '#2B6CB0',
  // colorInfoActive: '#1C3D5A',
  // colorInfoText: '#1890FF',
  // colorInfoTextHover: '#40A9FF',
  // colorInfoTextActive: '#096DD9',
  // colorInfoTextDisabled: '#434343',
  // colorTextBase: '#E8E8E8',
  // colorTextSecondary: '#BFBFBF',
  // colorTextTertiary: '#8C8C8C',
  // colorTextDisabled: '#595959',
  // colorTextHeading: '#FFFFFF',
  // colorTextLabel: '#BFBFBF',
  // colorTextPlaceholder: '#8C8C8C',
  colorFill: '#434459',
  // colorFillSecondary: '#262626',
  // colorFillTertiary: '#434343',
  // colorFillQuaternary: '#595959',
  // colorBgBase: '#141414',
  colorBgContainer: '#3a3e66',
  colorBgElevated: '#252544',
  colorBgLayout: '#0f102b'
  // colorBgSpotlight: '#1F1F1F',
  // colorBorder: '#434343',
  // colorBorderSecondary: '#595959',
  // colorBorderTertiary: '#8C8C8C',
  // colorBorderQuaternary: '#BFBFBF',
  // colorBorderBg: '#141414',
  // colorBgMask: 'rgba(0, 0, 0, 0.45)'
}

/**
 * 23243c
 * 252544
 * 434459
 */

const themeTokens = {
  light: lightThemeTokens,
  dark: darkThemeTokens
}

export { themeTokens }
